// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/ropehapi/desafio-stone/internal/application/usecase"
	"github.com/ropehapi/desafio-stone/internal/entity"
	"github.com/ropehapi/desafio-stone/internal/infra/database"
	"github.com/ropehapi/desafio-stone/internal/infra/web"
)

// Injectors from wire.go:

func NewCreatePersonUseCase(db *sql.DB) *usecase.CreatePersonUseCase {
	personRepository := database.NewPersonRepository(db)
	createPersonUseCase := usecase.NewCreatePersonUseCase(personRepository)
	return createPersonUseCase
}

func NewWebPersonHandler(db *sql.DB) *web.WebPersonHandler {
	personRepository := database.NewPersonRepository(db)
	webPersonHandler := web.NewWebPersonHandler(personRepository)
	return webPersonHandler
}

// wire.go:

var setPersonRepositoryDependecy = wire.NewSet(database.NewPersonRepository, wire.Bind(new(entity.PersonRepositoryInterface), new(*database.PersonRepository)))
