// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/ropehapi/desafio-stone/internal/application/usecase"
	"github.com/ropehapi/desafio-stone/internal/entity"
	"github.com/ropehapi/desafio-stone/internal/infra/database"
	"github.com/ropehapi/desafio-stone/internal/infra/web"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreatePersonUseCase(db *sql.DB) *usecase.CreatePersonUseCase {
	personRepository := database.NewPersonRepository(db)
	createPersonUseCase := usecase.NewCreatePersonUseCase(personRepository)
	return createPersonUseCase
}

func NewWebPersonHandler(db *sql.DB) *web.WebPersonHandler {
	personRepository := database.NewPersonRepository(db)
	webPersonHandler := web.NewWebPersonHandler(personRepository)
	return webPersonHandler
}

func NewWebRelationshipHandler(db *sql.DB) *web.WebRelationshipHandler {
	personRepository := database.NewPersonRepository(db)
	relationshipRepository := database.NewRelationshipRepository(db)
	webRelationshipHandler := web.NewWebRelationshipHandler(personRepository, relationshipRepository)
	return webRelationshipHandler
}

// wire.go:

var setPersonRepositoryDependecy = wire.NewSet(database.NewPersonRepository, wire.Bind(new(entity.PersonRepositoryInterface), new(*database.PersonRepository)))

var setRelationshipRepositoryDependecy = wire.NewSet(database.NewPersonRepository, database.NewRelationshipRepository, wire.Bind(new(entity.PersonRepositoryInterface), new(*database.PersonRepository)), wire.Bind(new(entity.RelationshipRepositoryInterface), new(*database.RelationshipRepository)))
